---
# This script needs to run as sudo
language: bash
sudo: true
dist: trust

# Install parallel
addons:
  apt:
    packages:
    - parallel
    - wget
    - curl

install:
  # Install ansible
  - pip install ansible

  # Check ansible version
  - ansible --version

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' >ansible.cfg

  # Install ansible-commons
  - ansible-galaxy install lucascbeyeler.commons

script:
  # Basic role syntax check
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
