[versions]
junit = "6.1.3"
junit-platform = "6.1.3"
unboundid-ldapsdk = "7.0.5"
wiremock = "3.13.2"
snakeyaml = "2.7"
picocli = "4.7.7"
logback = "1.6.3"
slf4j = "2.0.18"
sqlite-jdbc = "3.53.4.0"
aws-sdk = "2.29.52"
cucumber = "7.34.7"
shadow = "9.6.1"
foojay-resolver = "1.0.0"
spotbugs-plugin = "6.5.11"
spotbugs-annotations = "4.10.4"

[libraries]
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }
junit-platform-suite = { module = "org.junit.platform:junit-platform-suite", version.ref = "junit-platform" }
unboundid-ldapsdk = { module = "com.unboundid:unboundid-ldapsdk", version.ref = "unboundid-ldapsdk" }
wiremock = { module = "org.wiremock:wiremock", version.ref = "wiremock" }
snakeyaml = { module = "org.yaml:snakeyaml", version.ref = "snakeyaml" }
picocli = { module = "info.picocli:picocli", version.ref = "picocli" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
slf4j-jul-to-slf4j = { module = "org.slf4j:jul-to-slf4j", version.ref = "slf4j" }
sqlite-jdbc = { module = "org.xerial:sqlite-jdbc", version.ref = "sqlite-jdbc" }
aws-sdk-s3 = { module = "software.amazon.awssdk:s3", version.ref = "aws-sdk" }
aws-sdk-dynamodb = { module = "software.amazon.awssdk:dynamodb", version.ref = "aws-sdk" }
cucumber-java = { module = "io.cucumber:cucumber-java", version.ref = "cucumber" }
cucumber-junit-platform-engine = { module = "io.cucumber:cucumber-junit-platform-engine", version.ref = "cucumber" }
spotbugs-annotations = { module = "com.github.spotbugs:spotbugs-annotations", version.ref = "spotbugs-annotations" }

[plugins]
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
foojay-resolver-convention = { id = "org.gradle.toolchains.foojay-resolver-convention", version.ref = "foojay-resolver" }
spotbugs = { id = "com.github.spotbugs", version.ref = "spotbugs-plugin" }
