#!/bin/bash
################################################################################
# zmbackup - Bash script to hot backup and hot restore Zimbra Collaboration
#            Suite Opensource
#
# Copyright (C) 2021 Lucas Costa Beyeler <lucas.costab@outlook.com>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of version 2 of the GNU General Public
# License as published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307
# USA
#
################################################################################
# zmbkpose:
#
# 26/10/2010 - Version 1.0.5 - By Alan Nikitiuk Milani
#                              <alan.milani@4linux.com.br>
#                              <niki.milani@gmail.com>
#
#                              Bruno Gurgel
#                              <bruno@4linux.com.br>
#                              <bruno.gurgel@gmail.com>
#
# 24/05/2012 - Version 2.0 Beta - By William Felipe Welter
#                                 <william.welter@4linux.com.br>
#                                 <wfelipew@gmail.com>
################################################################################
# zmbackup:
#
# 06/02/2021 - Version 1.2.9  - By The Zimbra Community & Lucas Costa Beyeler
#                               <lucas.costab@outlook.com>
################################################################################
# parallel:
#
#   O. Tange (2011): GNU Parallel - The Command-Line Power Tool,
#  ;login: The USENIX Magazine, February 2011:42-47.
#
################################################################################
# LOADING ZMBACKUP LIBRARIES
################################################################################
# shellcheck source=lib/bash/HelpAction.sh
source /usr/local/lib/zmbackup/bash/HelpAction.sh
# shellcheck source=lib/bash/MiscAction.sh
source /usr/local/lib/zmbackup/bash/MiscAction.sh
# shellcheck source=lib/bash/NotifyAction.sh
source /usr/local/lib/zmbackup/bash/NotifyAction.sh
# shellcheck source=lib/bash/ParallelAction.sh
source /usr/local/lib/zmbackup/bash/ParallelAction.sh
# shellcheck source=lib/bash/ListAction.sh
source /usr/local/lib/zmbackup/bash/ListAction.sh
# shellcheck source=lib/bash/BackupAction.sh
source /usr/local/lib/zmbackup/bash/BackupAction.sh
# shellcheck source=lib/bash/RestoreAction.sh
source /usr/local/lib/zmbackup/bash/RestoreAction.sh
# shellcheck source=lib/bash/DeleteAction.sh
source /usr/local/lib/zmbackup/bash/DeleteAction.sh
# shellcheck source=lib/bash/MigrationAction.sh
source /usr/local/lib/zmbackup/bash/MigrationAction.sh
# shellcheck source=lib/bash/SessionAction.sh
source /usr/local/lib/zmbackup/bash/SessionAction.sh

################################################################################
# ZMBACKUP MAIN CODE
################################################################################
load_config
validate_config
export_function
export_vars
constant
case "$1" in
  "-f"|"--full" )
    checkpid
    case "$2" in
      "-dl"|"--distributionlist" )
        validate_account_args "$3" "$4" || exit 2
        sessionvars "$2"
        create_temp
        backup_main "$DLOBJECT" "$DLFILTER" "$3" "$4"
        rm -rf "$PID"
      ;;
      "-al"|"--alias" )
        validate_account_args "$3" "$4" || exit 2
        sessionvars "$2"
        create_temp
        backup_main "$ALOBJECT" "$ALFILTER" "$3" "$4"
        rm -rf "$PID"
      ;;
      "-ldp"|"--ldap" )
        validate_account_args "$3" "$4" || exit 2
        sessionvars "$2"
        create_temp
        backup_main "$ACOBJECT" "$ACFILTER" "$3" "$4"
        rm -rf "$PID"
      ;;
      "-m"|"--mail" )
        validate_account_args "$3" "$4" || exit 2
        sessionvars "$2"
        create_temp
        backup_main "$ACOBJECT" "$ACFILTER" "$3" "$4"
        rm -rf "$PID"
      ;;
      "-sig"|"--signature" )
        validate_account_args "$3" "$4" || exit 2
        sessionvars "$2"
        create_temp
        backup_main "$SIOBJECT" "$SIFILTER" "$3" "$4"
        rm -rf "$PID"
      ;;
      "-dom"|"--domain-backup" )
        sessionvars "$2"
        create_temp
        backup_main "$DOMOBJECT" "$DOMFILTER"
        rm -rf "$PID"
      ;;
      * )
        validate_account_args "$2" "$3" || exit 2
        sessionvars "$1"
        create_temp
        backup_main "$ACOBJECT" "$ACFILTER" "$2" "$3"
        rm -rf "$PID"
      ;;
    esac
  ;;
  "-i"|"--incremental" )
    validate_account_args "$2" "$3" || exit 2
    sessionvars "$1" 'TRUE'
    checkpid
    create_temp
    backup_main "$ACOBJECT" "$ACFILTER" "$2" "$3"
    rm -rf "$PID"
  ;;
  "-l"|"--list" )
    list_sessions
  ;;
  "-r"|"--restore" )
    create_temp
    checkpid
    case "$2" in
      "-dl"|"--distributionlist"|"-ldp"|"--ldap"|"-al"|"--alias"|"-sig"|"--signature")
        case "$3" in
          "-a"|"--account"|"-d"|"--domain")
            if ! validate_session_id "$4"; then
              printf "\n\nError! Invalid session ID: %s\n\n" "$4"; exit 2
            fi
            restore_main_ldap "$4" "$5"
            ERRCODE=$?
          ;;
          * )
            if ! validate_session_id "$3"; then
              printf "\n\nError! Invalid session ID: %s\n\n" "$3"; exit 2
            fi
            restore_main_ldap "$3" "$4"
            ERRCODE=$?
          ;;
        esac
        rm -rf "$PID"
      ;;
      "-dom"|"--domain-backup" )
        if ! validate_session_id "$3"; then
          printf "\n\nError! Invalid session ID: %s\n\n" "$3"; exit 2
        fi
        restore_main_domain "$3" "$4"
        ERRCODE=$?
        rm -rf "$PID"
      ;;
      "-m"|"--mail" )
        if ! validate_session_id "$3"; then
          printf "\n\nError! Invalid session ID: %s\n\n" "$3"; exit 2
        fi
        restore_main_mailbox "$3" "$4" "$5"
        ERRCODE=$?
        rm -rf "$PID"
      ;;
      "-ro"|"--restoreOnAccount" )
        if [ -z "$4" ] || [ -z "$5" ]; then
          show_help
          printf "\n\nError! Please inform the account that should be restored, and when the restore should be placed.\n\n"
          exit 2
        else
          if ! validate_session_id "$3"; then
            printf "\n\nError! Invalid session ID: %s\n\n" "$3"; exit 2
          fi
          if ! validate_email "$4"; then
            printf "\n\nError! Invalid email address: %s\n\n" "$4"; exit 2
          fi
          if ! validate_email "$5"; then
            printf "\n\nError! Invalid email address: %s\n\n" "$5"; exit 2
          fi
          restore_main_mailbox "$3" "$4" "$5"
          ERRCODE=$?
          rm -rf "$PID"
        fi
      ;;
      * )
        if [[ "$2" == "full"* || "$2" == "inc"* ]]; then
          if ! validate_session_id "$2"; then
            printf "\n\nError! Invalid session ID: %s\n\n" "$2"; exit 2
          fi
          restore_main_ldap "$2" "$3" "$4"
          ERRCODE=$?
          restore_main_mailbox "$2" "$3" "$4"
          MAILBOX_ERRCODE=$?
          [[ $MAILBOX_ERRCODE -ne 0 ]] && ERRCODE=$MAILBOX_ERRCODE
          rm -rf "$PID"
        else
          show_help
          printf "\n\nError! Invalid parameters for restore\n"
        fi
      ;;
    esac
  ;;
  "-d"|"--delete" )
    if [ -z "$2" ]; then
      show_help
      printf "\n\nError! Please inform the session that should be deleted\n\n"
    else
      if ! validate_session_id "$2"; then
        printf "\n\nError! Invalid session ID: %s\n\n" "$2"
        exit 2
      fi
      checkpid
      delete_one "$2"
      ERRCODE=$?
      rm -rf "$PID"
    fi
  ;;
  "-hp"|"--housekeep")
    checkpid
    delete_old
    clean_empty
    rm -rf "$PID"
  ;;
  "-t"|"--truncate")
    if [ -n "$2" ] && [ "--force-clean" == "$2" ]; then
      checkpid
      leeroy_jenkins
      clean_empty
      rm -rf "$PID"
    else
      echo "This action is irreversible - Use the option --force-clean to override this message"
    fi
  ;;
  "-h"|"--help" )
    show_help
  ;;
  "-v"|"--version" )
    echo "zmbackup version: $(cat /usr/local/lib/zmbackup/VERSION 2>/dev/null || echo "unknown")"
  ;;
  "-mg"|"--migrate" )
    checkpid
    migration
    rm -rf "$PID"
  ;;
  * )
    show_help
    printf "\n\nError! Incorrect options\n\n"
  ;;
esac
exit "${ERRCODE:-0}"
