#!/bin/bash
################################################################################
# zmbackup - Bash script to hot backup and hot restore Zimbra Collaboration
#            Suite Opensource
#
# Copyright (C) 2017 Lucas Costa Beyeler <lucas.costab@outlook.com>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of version 2 of the GNU General Public
# License as published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307
# USA
#
################################################################################
# sendreport:
#
# 24/03/2017 - Version 1.1.0 -  By Lucas Costa Beyeler
#                               <lucas.beyeler@4linux.com.br>
#                               <lucas.costab@outlook.com>
################################################################################
# parallel:
#
#   O. Tange (2011): GNU Parallel - The Command-Line Power Tool,
#  ;login: The USENIX Magazine, February 2011:42-47.
#
################################################################################
# CHECK IF THE ZMBACKUP.CONF IS CONFIGURED CORRECTLY
################################################################################

# Function to notify when the backup process began through e-mail
notify_email_begin()
{
  echo "Subject: Backup $1 begin at $(date)" >> /tmp/mail.txt
  echo "This e-mail is just to inform you that the backup process that you \
        scheduled already begin." >> /tmp/mail.txt
  echo "Depending the quantity of accounts you have, this process can last \
        hours or days." >> /tmp/mail.txt
  echo "Don't worry, we will inform you when the process finish." >> /tmp/mail.txt
  echo "" >> /tmp/mail.txt
  echo "Regards," >> /tmp/mail.txt
  echo "Zmbackup Team" >> /tmp/mail.txt
  echo "" >> /tmp/mail.txt
  sendmail $EMAIL_NOTIFY < /tmp/mail.txt
  rm /tmp/mail.txt
}

# Function to notify when the backup process finish and the status through e-mail
notify_email_finish()
{
  if [ $1 == "OK" ]; then
    total=$(du -h $WORKDIR/$SESSION | awk {'print $1'});
    echo "Subject: Backup $2 complete at $(date)" >> /tmp/mail.txt
    echo "This e-mail is just to inform you that the backup process that you \
          scheduled already finish with the status SUCCESS." >> /tmp/mail.txt
    echo -e "\r\nTotal: $total " >> /tmp/mail.txt
    echo "" >> /tmp/mail.txt
    echo "Regards," >> /tmp/mail.txt
    echo "Zmbackup Team" >> /tmp/mail.txt
    echo "" >> /tmp/mail.txt
    echo "Summary of files:" >> /tmp/mail.txt
    cat $TEMPSESSION >> /tmp/mail.txt
  else
    echo "Subject: Backup $2 complete at $(date)" >> /tmp/mail.txt
    echo "This e-mail is just to inform you that the backup process that you \
          scheduled already finish with the status FAILURE." >> /tmp/mail.txt
    echo "Check and correct what is preventing the backup before the next run." >> /tmp/mail.txt
    echo "" >> /tmp/mail.txt
    echo "Regards," >> /tmp/mail.txt
    echo "Zmbackup Team" >> /tmp/mail.txt
    echo "" >> /tmp/mail.txt
    echo "Summary of files:" >> /tmp/mail.txt
    cat $TEMPSESSION >> /tmp/mail.txt
  fi
  sendmail $EMAIL_NOTIFY < /tmp/mail.txt
  rm /tmp/mail.txt
  rm -f "$TEMPSESSION"
}
