#!/bin/bash
################################################################################
# zmbackup - Bash script to hot backup and hot restore Zimbra Collaboration
#            Suite Opensource
#
# Copyright (C) 2017 Lucas Costa Beyeler <lucas.costab@outlook.com>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of version 2 of the GNU General Public
# License as published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307
# USA
#
################################################################################
# zmbkpose:
#
# 26/10/2010 - Version 1.0.5 - By Alan Nikitiuk Milani
#                              <alan.milani@4linux.com.br>
#                              <niki.milani@gmail.com>
#
#                              Bruno Gurgel
#                              <bruno@4linux.com.br>
#                              <bruno.gurgel@gmail.com>
#
# 24/05/2012 - Version 2.0 Beta - By William Felipe Welter
#                                 <william.welter@4linux.com.br>
#                                 <wfelipew@gmail.com>
################################################################################
# zmbackup:
#
# 13/03/2017 - Version 1.1.0  - By Lucas Costa Beyeler
#                               <lucas.beyeler@4linux.com.br>
#                               <lucas.costab@outlook.com>
################################################################################
# parallel:
#
#   O. Tange (2011): GNU Parallel - The Command-Line Power Tool,
#  ;login: The USENIX Magazine, February 2011:42-47.
#
################################################################################
# SET INTERNAL VARIABLE
################################################################################

# LDAP OBJECT
export DLOBJECT="(objectclass=zimbraDistributionList)"
export ACOBJECT="(objectclass=zimbraAccount)"
export ALOBJECT="(objectclass=zimbraAlias)"

# LDAP FILTER
export ACFILTER="zimbraMailDeliveryAddress"
export DLFILTER="mail"
export ALFILTER="uid"

################################################################################
# ZMBACKUP FUNCTIONS
################################################################################

load_config(){
  source /etc/zmbackup/zmbackup.conf
  source /opt/zimbra/.bashrc
}

# Create the temporary files
create_temp(){
  export TEMPDIR=$(mktemp -d $WORKDIR/XXXX)
  export TEMPSESSION=$(mktemp)
  export TEMPACCOUNT=$(touch /tmp/accounts.txt)
  export TEMPINCACCOUNT=$(mktemp)
}

# Clear all the temporary files
clear_temp(){
  rm -rf $TEMPSESSION $TEMPACCOUNT $TEMPINCACCOUNT $TEMPDIR
}

################################################################################
# LOAD CLASS FILES
################################################################################
source /usr/local/share/zmbackup/backup
source /usr/local/share/zmbackup/helpme
source /usr/local/share/zmbackup/list
source /usr/local/share/zmbackup/restore
source /usr/local/share/zmbackup/sendreport
source /usr/local/share/zmbackup/validate

################################################################################
# MAIN CODE - HERE IS WHERE THE MAGIC HAPPENS
################################################################################

validate
load_config

case "$1" in
  "-f"|"--full" )
    create_temp
    echo "Running the Full Backup - Please wait..."
    case "$2" in
      "-dl"|"--distributionlist" )
        backup_dl $3
      ;;
      "-al"|"--alias" )
        backup_alias $3
      ;;
      "-ldp"|"--ldap" )
        ldap_bkp $3
      ;;
      * )
        backup_full $2
    esac
    echo "Backup finished!"
    clear_temp
  ;;
  "-i"|"--incremental" )
    create_temp
    echo "Running the Incremental Backup - Please wait..."
    backup_incremental $2
    echo "Backup finished!"
    clear_temp
  ;;
  "-l"|"--list" )
    list_sessions
  ;;
  "-r"|"--restore" )
    create_temp
    case "$2" in
      "-dl"|"--distributionlist" )
        if [ -z "$3" ]; then
          show_help
          printf "\n\nError! Please inform the session that should be restored\n\n"
        else
          restore_accounts_ldap $3 $4
        fi
      ;;
      "-al"|"--alias" )
        if [ -z "$3" ]; then
          show_help
          printf "\n\nError! Please inform the session that should be restored\n\n"
        else
          restore_accounts_ldap $3 $4
        fi
      ;;
      "-ldp"|"--ldap" )
      if [ -z "$3" ]; then
        show_help
        printf "\n\nError! Please inform the session that should be restored\n\n"
      else
        restore_accounts_ldap $3 $4
      fi
      ;;
      "-ro"|"--restoreOnAccount" )
      if [ -z "$3" ] || [ -z "$4" ] || [ -z "$5" ]; then
        show_help
        printf "\n\nError! Please inform the session, the account that should be restored, and when the restore should be placed.\n\n"
      else
        restore_accounts_mail $5 $3 $4
      fi
      ;;
      "-m"|"--mail" )
      if [ -z "$3" ]; then
        show_help
        printf "\n\nError! Please inform the session that should be restored\n\n"
      else
        restore_accounts_mail $3 $4
      fi
      ;;
      * )
        show_help
        printf "\n\nError! Incorrect options\n\n"
      ;;
    esac
    clear_temp
  ;;
  "-d"|"--delete" )
  if [ -z "$2" ]; then
    show_help
    printf "\n\nError! Please inform the session that should be deleted\n\n"
  else
    rotate_backup $2
  fi
  ;;
  "-h"|"--help" )
    show_help
  ;;
  "-v"|"--version" )
    echo "zmbackup version: 1.1.0"
  ;;
  * )
    show_help
    printf "\n\nError! Incorrect options\n\n"
  ;;
esac
